name: Frontend CI with SonarCloud

on:
  push:
    branches:
      - main
      - feature/frontend-setup
  pull_request:
    branches:
      - main

jobs:
  frontend-ci:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: npm

      - name: Install dependencies
        run: npm install

      - name: Build frontend
        run: npm run build

      - name: SonarCloud analysis
        uses: SonarSource/sonarcloud-github-action@v2
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args: >
            -Dsonar.projectKey=sakthi-meera-007_ideasync-frontend
            -Dsonar.organization=sakthi-meera-007
            -Dsonar.sources=src
